### ISSUE TITLE
Process schemas nested inside another document (like in OpenAPI schema)

### ISSUE THREAD

**Issue by Envek** [mokkabonna/json-schema-merge-allof#26]
First of all, thank you for this awesome library! It saved me a lot of effort for rewriting API specification due to `allOf` and `additionalProperties: false` (see http://json-schema.org/understanding-json-schema/reference/combining.html#id5 and https://stackoverflow.com/questions/22689900/json-schema-allof-with-additionalproperties for details) but still requires some additional work to use it with [OpenAPI](https://swagger.io/specification/) specs.

**Problem**
In OpenAPI specs, JSON schemas for requests and responses are located deep inside the API spec:
<details>
<summary>Fragment of an example OpenAPI spec for reference</summary>

```yml
openapi: 3.0.1
info:
  title: Example Application API
  version: v1
paths:
  /applications:
    get:
      summary: Gets a list of Applications.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExtendedApplication'
components:
  schemas:
    Application:
      required:
        - name
        - id
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      additionalProperties: false
    ExtendedApplication:
      allOf:
        - $ref: '#/components/schemas/Application'
        - type: object
          properties:
            additionalInfo:
              type: string
```
</details>

And if I feed whole spec into `mergeAllOf` then all the subschemas won't get merged automatically. Is there any option for this?

**Workaround**

Write recursive function to find subschemas in a swagger spec.

```js
async function preprocessOpenapiSpec(apiSpec) {
  const schema = await $RefParser.dereference(apiSpec)

  function mergeAllOfRecursively(candidate, parent, k) {
    if (typeof candidate !== "object") return

    if (candidate.allOf) {
      parent[k] = mergeAllOf(candidate, { ignoreAdditionalProperties: true, deep: true })
    } else {
      for (const [key, value] of Object.entries(candidate)) {
        mergeAllOfRecursively(value, candidate, key)
      }
    }
  }

  for (const [key, value] of Object.entries(schema)) {
    mergeAllOfRecursively(value, apiSpec, key)
  }

  return schema
}
```

**Comment by mokkabonna** [comment]
Most of what you posted there is not a json schema, only under **component -> schemas** are actually json schemas. The first part (paths etc) are not json schemas. Just JSON.

I think merging a openapi specification is not in the scope of this module.

Perhaps the best thing would be to create a wrapper library that deals with open api and then calls this library whenever it encounters an actual json schema.

---

![image](https://user-images.githubusercontent.com/230877/107009359-3dd3a280-6795-11eb-8c05-eb1eb1ae8594.png)

**Comment by Envek** [comment]
In OpenAPI specs, JSON schemas are also located/referred in `paths.**.responses` and `paths.**.requestBody` (and maybe somewhere else). And after dereferencing with `json-schema-ref-parser` anything inside `components.schemas` isn't used anymore (because this section is designed just to place schemas to `$ref` to).

---

Anyway, your library works as expected after adding some wrapping code, so this issue is meant to start discussion and provide solution for other folks with the same problem as mine.

**Comment by mokkabonna** [comment]
True, also schema under responses -> content -> application/json -> schema
